workflows:
  ios-workflow:
    name: LibGDX iOS Build

    environment:
      xcode: latest
      java: 17


    scripts:
      - name: Grant permission
        script: chmod +x gradlew

      - name: Build iOS IPA
        script: ./gradlew ios:createIPA

    artifacts:
      - ios/build/robovm/**/*.ipa